# StyLua 的配置文件，StyLua 是一个用于格式化 Lua 代码的工具。它可以自动调整代码的样式，确保一致性和可读性

column_width = 120
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferDouble"
call_parentheses = "None"
collapse_simple_statement = "Always"
