# 配置 Selene，一个用于静态分析 Lua 代码的工具。Selene 可以帮助开发者检测代码中的潜在错误、不规范的代码风格等问题。

std = "neovim"

[rules]
global_usage = "allow"
if_same_then_else = "allow"
incorrect_standard_library_use = "allow"
mixed_table = "allow"
multiple_statements = "allow"
